---
title: "Project 1: Cleaning Data and Exploratory Plots"
author: "Ashley Kim"
date: "2/10/2023"
output: html_document
---
```{r, include=FALSE}
# Installing libraries

library(tidyverse)
library(plotly)
library(htmltools)
library(caret)
library(NbClust)
library(dplyr)
```

```{r}
listings = read_csv("Project1/listings.csv")
listings <- listings[,-c(3,4,5,7,8,11,13:18)]
colnames(listings)[1] ="listing_id"
```

```{r}
reviews = read_csv("Project1/reviews.csv")
```

```{r}
airbnb <- merge(reviews,listings,by="listing_id")
airbnb_filtered <- airbnb %>% 
    filter(str_detect(comments, '\\b(clean|quiet|safe|spacious|responsive|comfortable|accomodating|convenient| relaxing|great view|dirty|loud|unsafe|rude|disappointed|far|unresponsive|invasive|smelly|messy)\\b'))

airbnb_positive <- airbnb %>% 
    filter(str_detect(comments, '\\b(clean|quiet|safe|spacious|responsive|comfortable|accomodating|convenient| relaxing|great view)\\b'))%>% 
    filter(str_detect(neighbourhood, '\\b(Dupont Circle, Connecticut Avenue/K Street)\\b'))
                      
airbnb_negative <- airbnb %>% 
    filter(str_detect(comments, '\\b(dirty|loud|unsafe|rude|disappointed|far|unresponsive|invasive|smelly|messy)\\b'))%>% 
    filter(str_detect(neighbourhood, '\\b(Dupont Circle, Connecticut Avenue/K Street)\\b'))
```

```{r}
library(wordcloud)
library(RColorBrewer)
library(wordcloud2)
```

```{r}
# positive word cloud
library(tm)
text <- airbnb_positive$comments
docs <- Corpus(VectorSource(text))
docs <- docs %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeWords, stopwords("english"))
dtm <- TermDocumentMatrix(docs) 
matrix <- as.matrix(dtm) 
words <- sort(rowSums(matrix),decreasing=TRUE) 
df <- data.frame(word = names(words),freq=words)
set.seed(1234) # for reproducibility 
wordcloud(words = df$word, freq = df$freq, min.freq = 10,max.words=200, random.order=FALSE, rot.per=0.35,  colors=brewer.pal(8, "Dark2"))
```
```{r}
# negative word cloud
library(tm)
text <- airbnb_negative$comments
docs <- Corpus(VectorSource(text))
docs <- docs %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeWords, stopwords("english"))
dtm <- TermDocumentMatrix(docs) 
matrix <- as.matrix(dtm) 
words <- sort(rowSums(matrix),decreasing=TRUE) 
df <- data.frame(word = names(words),freq=words)
set.seed(1234) # for reproducibility 
wordcloud(words = df$word, freq = df$freq, min.freq = 10,max.words=200, random.order=FALSE, rot.per=0.35,  colors=brewer.pal(8, "Dark2"))
```


```{r}
# bar plot by neighbourhood
ggplot(airbnb_filtered, aes(x = neighbourhood)) +
  geom_bar() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_x_discrete(label=abbreviate)
ggsave("countplot.jpg")
```

